const avaliacoes = {
  coelhos: [
    {
      nome: "Pedro",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "O Pulinho é muito brincalhão e adorável.",
      estrelas: 5,
    },
    {
      nome: "Julia",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem:
        "Os coelhos são muito fofos e as informações ajudaram bastante.",
      estrelas: 5,
    },
    {
      nome: "Marcos",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Gostei muito da experiência de conhecer os animais.",
      estrelas: 4,
    },
    {
      nome: "Beatriz",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "O site é fácil de usar e encontrei várias informações.",
      estrelas: 5,
    },
    {
      nome: "Camila",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Adorei conhecer os coelhinhos. São todos muito fofos!",
      estrelas: 5,
    },
    {
      nome: "Thiago",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "As informações sobre alimentação e cuidados foram ótimas.",
      estrelas: 4,
    },
    {
      nome: "Larissa",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Foi muito legal conhecer melhor a personalidade dos coelhos.",
      estrelas: 5,
    },
    {
      nome: "Felipe",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Encontrei tudo o que precisava saber de forma bem simples.",
      estrelas: 5,
    },
    {
      nome: "Sofia",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Os coelhos são encantadores e o site está muito bonito.",
      estrelas: 5,
    },
    {
      nome: "Henrique",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Coelho",
      mensagem: "Gostei bastante das informações e da facilidade para navegar.",
      estrelas: 4,
    },
  ],

  calopsitas: [
    {
      nome: "Raven",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem:
        "Raven é uma calopsita incrível! Ela é muito carinhosa e adora cantar.",
      estrelas: 5,
    },
    {
      nome: "Lucas",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "Adorei conhecer melhor as calopsitas disponíveis para adoção.",
      estrelas: 5,
    },
    {
      nome: "Amanda",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "As informações sobre os cuidados são muito úteis.",
      estrelas: 4,
    },
    {
      nome: "Gabriel",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "Muito fácil encontrar informações sobre os animais.",
      estrelas: 5,
    },
    {
      nome: "Isabela",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "Sempre gostei de calopsitas e adorei aprender mais sobre elas.",
      estrelas: 5,
    },
    {
      nome: "Bruno",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "As dicas de alimentação e cuidados foram muito interessantes.",
      estrelas: 4,
    },
    {
      nome: "Manuela",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "São animais muito carinhosos e divertidos. Gostei bastante!",
      estrelas: 5,
    },
    {
      nome: "Gustavo",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "O conteúdo é simples de entender e muito bem organizado.",
      estrelas: 5,
    },
    {
      nome: "Alice",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "Adorei as informações sobre comportamento das calopsitas.",
      estrelas: 5,
    },
    {
      nome: "André",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Calopsita",
      mensagem: "Foi uma experiência muito boa conhecer esses animais.",
      estrelas: 4,
    },
  ],

  gatos: [
    {
      nome: "Barto",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Barto é um gato carinhoso que procura um lar cheio de amor.",
      estrelas: 5,
    },
    {
      nome: "Mariana",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem:
        "Adorei conhecer os gatos disponíveis. O site ficou muito organizado.",
      estrelas: 5,
    },
    {
      nome: "João",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "As informações dos gatos são claras e fáceis de encontrar.",
      estrelas: 4,
    },
    {
      nome: "Carla",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Gostei bastante da página e das informações dos animais.",
      estrelas: 5,
    },
    {
      nome: "Eduardo",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Os gatos são lindos e as descrições ajudam bastante na escolha.",
      estrelas: 5,
    },
    {
      nome: "Valentina",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Achei muito legal poder conhecer a personalidade de cada gato.",
      estrelas: 5,
    },
    {
      nome: "Caio",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "O site é bem organizado e encontrei as informações rapidamente.",
      estrelas: 4,
    },
    {
      nome: "Helena",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Sempre gostei de gatos e adorei conhecer esses novos amiguinhos.",
      estrelas: 5,
    },
    {
      nome: "Mateus",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "As informações sobre comportamento foram muito úteis.",
      estrelas: 5,
    },
    {
      nome: "Luiza",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Gato",
      mensagem: "Uma página simples, bonita e com ótimas informações.",
      estrelas: 4,
    },
  ],

  caes: [
    {
      nome: "Rafael",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "O Rex parece ser muito carinhoso e brincalhão.",
      estrelas: 5,
    },
    {
      nome: "Fernanda",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Gostei muito das informações sobre os cães.",
      estrelas: 5,
    },
    {
      nome: "Daniel",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "O site facilita bastante a busca por animais.",
      estrelas: 4,
    },
    {
      nome: "Laura",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Muito bom poder conhecer as características de cada cachorro.",
      estrelas: 5,
    },
    {
      nome: "Vinícius",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Adorei conhecer os cães. As descrições são muito completas.",
      estrelas: 5,
    },
    {
      nome: "Bianca",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Os cachorros parecem muito dóceis e bem cuidados.",
      estrelas: 5,
    },
    {
      nome: "Rodrigo",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Gostei das informações sobre o comportamento de cada cão.",
      estrelas: 4,
    },
    {
      nome: "Nicole",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Foi muito fácil encontrar informações sobre os cachorros.",
      estrelas: 5,
    },
    {
      nome: "Leonardo",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "A página ficou muito bonita e os animais são encantadores.",
      estrelas: 5,
    },
    {
      nome: "Ana",
      foto: "/img/perfil-padrao.png",
      tipoPet: "Cachorro",
      mensagem: "Gostei muito das dicas e das informações para quem quer adotar.",
      estrelas: 5,
    },
  ],
};
